[theme]
base = "light"
primaryColor = "#1F6BFF"
backgroundColor = "#EAF4FF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F1F33"

[client]
toolbarMode = "minimal"

[server]
headless = true

[browser]
gatherUsageStats = false